export const TYPE = [
	"upcoming", "ongoing", "concluded"
];

export const DATA = [
	{	'type': 'upcoming',
		'name': 'Arena Tournament',
		'duration': '1:45 mins',
		'start_time': '13:00 UTC',
		'time_control': '3+0',
		'participants': 15,
		'mode': 'Rated'
	},
	{	'type': 'upcoming',
		'name': 'Arena Tournament',
		'duration': '2 hours',
		'start_time': '13:00 UTC',
		'time_control': '3+0',
		'participants': 15,
		'mode': 'Rated'
	},
	{	'type': 'upcoming',
		'name': 'Arena Tournament',
		'duration': '1 hour',
		'start_time': '13:00 UTC',
		'time_control': '3+0',
		'participants': 15,
		'mode': 'Rated'
	},
	{	'type': 'upcoming',
		'name': 'Arena Tournament',
		'duration': '30 minutes',
		'start_time': '13:00 UTC',
		'time_control': '3+0',
		'participants': 15,
		'mode': 'Rated'
	},
	{	'type': 'upcoming',
		'name': 'Arena Tournament',
		'duration': '1:45 mins',
		'start_time': '13:00 UTC',
		'time_control': '3+0',
		'participants': 15,
		'mode': 'Rated'
	},
	{	'type': 'upcoming',
		'name': 'Arena Tournament',
		'duration': '2 hours',
		'start_time': '13:00 UTC',
		'time_control': '3+0',
		'participants': 15,
		'mode': 'Rated'
	},
	{	'type': 'upcoming',
		'name': 'Test1',
		'duration': '1:45 mins',
		'start_time': '13:00 UTC',
		'time_control': '3+0',
		'participants': 15,
		'mode': 'Rated'
	},
	{	'type': 'upcoming',
		'name': 'Test2',
		'duration': '1:45 mins',
		'start_time': '13:00 UTC',
		'time_control': '3+0',
		'participants': 15,
		'mode': 'Rated'
	},
	{	'type': 'upcoming',
		'name': 'Test3',
		'duration': '1:45 mins',
		'start_time': '13:00 UTC',
		'time_control': '3+0',
		'participants': 15,
		'mode': 'Rated'
	},
	{	'type': 'upcoming',
		'name': 'Test4',
		'duration': '1:45 mins',
		'start_time': '13:00 UTC',
		'time_control': '3+0',
		'participants': 15,
		'mode': 'Rated'
	},
	{	'type': 'upcoming',
		'name': 'Test5',
		'duration': '1:45 mins',
		'start_time': '13:00 UTC',
		'time_control': '3+0',
		'participants': 15,
		'mode': 'Rated'
	},
	{	'type': 'upcoming',
		'name': 'Test6',
		'duration': '1:45 mins',
		'start_time': '13:00 UTC',
		'time_control': '3+0',
		'participants': 15,
		'mode': 'Rated'
	},
	{	'type': 'upcoming',
		'name': 'Test7',
		'duration': '1:45 mins',
		'start_time': '13:00 UTC',
		'time_control': '3+0',
		'participants': 15,
		'mode': 'Rated'
	},
	{	'type': 'upcoming',
		'name': 'Test8',
		'duration': '1:45 mins',
		'start_time': '13:00 UTC',
		'time_control': '3+0',
		'participants': 15,
		'mode': 'Rated'
	},
	{	'type': 'upcoming',
		'name': 'Test9',
		'duration': '1:45 mins',
		'start_time': '13:00 UTC',
		'time_control': '3+0',
		'participants': 15,
		'mode': 'Rated'
	},
	{	'type': 'upcoming',
		'name': 'Test10',
		'duration': '1:45 mins',
		'start_time': '13:00 UTC',
		'time_control': '3+0',
		'participants': 15,
		'mode': 'Rated'
	},
	{	'type': 'upcoming',
		'name': 'Test11',
		'duration': '1:45 mins',
		'start_time': '13:00 UTC',
		'time_control': '3+0',
		'participants': 15,
		'mode': 'Rated'
	},
	{	'type': 'upcoming',
		'name': 'Test12',
		'duration': '1:45 mins',
		'start_time': '13:00 UTC',
		'time_control': '3+0',
		'participants': 15,
		'mode': 'Rated'
	},
	{	'type': 'upcoming',
		'name': 'Test13',
		'duration': '1:45 mins',
		'start_time': '13:00 UTC',
		'time_control': '3+0',
		'participants': 15,
		'mode': 'Rated'
	},

	{	'type': 'ongoing',
		'name': 'Arena Tournament',
		'duration': '1:45 mins',
		'start_time': '13:00 UTC',
		'time_control': '3+0',
		'participants': 15,
		'mode': 'Rated'
	},
	{	'type': 'ongoing',
		'name': 'Arena Tournament',
		'duration': '2 hours',
		'start_time': '13:00 UTC',
		'time_control': '3+0',
		'participants': 15,
		'mode': 'Rated'
	},
	{	'type': 'ongoing',
		'name': 'Arena Tournament',
		'duration': '1 hour',
		'start_time': '13:00 UTC',
		'time_control': '3+0',
		'participants': 15,
		'mode': 'Rated'
	},
	{	'type': 'ongoing',
		'name': 'Arena Tournament',
		'duration': '30 minutes',
		'start_time': '13:00 UTC',
		'time_control': '3+0',
		'participants': 15,
		'mode': 'Rated'
	},
	{	'type': 'ongoing',
		'name': 'Arena Tournament',
		'duration': '1:45 mins',
		'start_time': '13:00 UTC',
		'time_control': '3+0',
		'participants': 15,
		'mode': 'Rated'
	},
	{	'type': 'ongoing',
		'name': 'Arena Tournament',
		'duration': '2 hours',
		'start_time': '13:00 UTC',
		'time_control': '3+0',
		'participants': 15,
		'mode': 'Rated'
	},

	{	'type': 'concluded',
		'name': 'Arena Tournament',
		'duration': '1:45 mins',
		'start_time': '13:00 UTC',
		'time_control': '3+0',
		'participants': 15,
		'mode': 'Rated'
	},
	{	'type': 'concluded',
		'name': 'Arena Tournament',
		'duration': '2 hours',
		'start_time': '13:00 UTC',
		'time_control': '3+0',
		'participants': 15,
		'mode': 'Rated'
	},
	{	'type': 'concluded',
		'name': 'Arena Tournament',
		'duration': '1 hour',
		'start_time': '13:00 UTC',
		'time_control': '3+0',
		'participants': 15,
		'mode': 'Rated'
	},
	{	'type': 'concluded',
		'name': 'Arena Tournament',
		'duration': '30 minutes',
		'start_time': '13:00 UTC',
		'time_control': '3+0',
		'participants': 15,
		'mode': 'Rated'
	},
	{	'type': 'concluded',
		'name': 'Arena Tournament',
		'duration': '1:45 mins',
		'start_time': '13:00 UTC',
		'time_control': '3+0',
		'participants': 15,
		'mode': 'Rated'
	},
	{	'type': 'concluded',
		'name': 'Arena Tournament',
		'duration': '2 hours',
		'start_time': '13:00 UTC',
		'time_control': '3+0',
		'participants': 15,
		'mode': 'Rated'
	},
]